### ISSUE TITLE
Error when not running in verbose mode

### ISSUE THREAD

**Issue by RoelN** [13rac1/scfbuild#6]
`bin/scfbuild -o testfont.ttf -g ./src/svg -s ./src/svg`

```
Traceback (most recent call last):
  File "/Users/roel/code/scfbuild/bin/scfbuild", line 17, in <module>
    sys.exit(main())
  File "/Users/roel/code/scfbuild/scfbuild/main.py", line 123, in main
    builder = Builder(conf)
  File "/Users/roel/code/scfbuild/scfbuild/builder.py", line 47, in __init__
    if self.conf['verbose']:
KeyError: u'verbose'
```

Adding the `-v` flag works.

**Comment by 13rac1** [comment]
Ah yes! I encountered this while building the xerographer fonts, but forgot it.
